"""PostgreSQL adapter defaulting to the seven Hermes-owned kanban tables.

Reuse the state backend's rows, SQL splitter and binding lexer, not its session
SQL rewrites, schema, FTS or reconnect policy. Schema comes from the canonical
kanban DDL and additive migrations. Catalog access, initialization and write
transactions are explicit dialect operations. No SQLite fallback, statement
replay, guild mapping, cross-database ATTACH, or host-app import is provided.
Projects reuses the adapter with its own explicitly closed dialect metadata.
"""

from __future__ import annotations

import contextlib
import os
import re
import sqlite3

from hermes_cli.kanban_persistence import (
    TABLE_KEYS as _TABLE_KEYS,
)
from hermes_state_postgres import (
    _PostgresConnection,
    _PostgresCursor,
    _split_sql_statements,
    _translate_bindings,
)

_IDENTITY_TABLES = frozenset({
    "task_comments",
    "task_events",
    "task_runs",
    "task_attachments",
})
_INSERT = re.compile(
    r"^\s*INSERT\s+(?:OR\s+(IGNORE|REPLACE)\s+)?INTO\s+(\w+)\s*\(",
    re.IGNORECASE,
)


def _schema_statement(sql):
    """Translate canonical core-store CREATE/ALTER column declarations."""
    sql = re.sub(
        r"\bINTEGER PRIMARY KEY AUTOINCREMENT\b",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        sql,
    )
    return re.sub(r"\bINTEGER\b", "BIGINT", sql)


class PostgresDialect:
    backend = "postgres"
    uses_sqlite_files = False
    table_keys = _TABLE_KEYS
    identity_tables = _IDENTITY_TABLES
    store_name = "kanban"

    def check_table(self, table):
        if table not in self.table_keys:
            raise ValueError(
                f"Table is outside the {self.store_name} persistence contract"
            )

    def order_by(self, expression):
        terms = []
        for term in expression.split(", "):
            match = re.fullmatch(
                r"(?:created_at|id|priority|status|assignee|title|started_at) "
                r"(ASC|DESC)(?: NULLS (FIRST|LAST))?",
                term,
            )
            if match is None:
                raise ValueError("Unknown kanban sort expression")
            if match.group(2) is None:
                term += " NULLS FIRST" if match.group(1) == "ASC" else " NULLS LAST"
            terms.append(term)
        return ", ".join(terms)

    def table_info(self, conn, table):
        self.check_table(table)
        return conn.execute(
            "SELECT a.attname AS name, a.attidentity AS identity, "
            "CASE WHEN a.atttypid IN ('int8'::regtype, 'int4'::regtype) "
            "THEN 'INTEGER' ELSE upper(format_type(a.atttypid, a.atttypmod)) END AS type, "
            "EXISTS (SELECT 1 FROM pg_index i WHERE i.indrelid = a.attrelid "
            "AND i.indisprimary AND a.attnum = ANY(i.indkey)) AS pk "
            "FROM pg_attribute a JOIN pg_class c ON c.oid = a.attrelid "
            "JOIN pg_namespace n ON n.oid = c.relnamespace "
            "WHERE n.nspname = current_schema() AND c.relname = ? "
            "AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum",
            (table,),
        ).fetchall()

    def table_exists(self, conn, table):
        self.check_table(table)
        return (
            conn.execute(
                "SELECT 1 FROM information_schema.tables "
                "WHERE table_schema = current_schema() AND table_name = ?",
                (table,),
            ).fetchone()
            is not None
        )

    @contextlib.contextmanager
    def write_txn(self, conn, *, allow_nested=False):
        if conn.in_transaction and not allow_nested:
            raise RuntimeError(
                "write_txn() cannot nest; opt in with allow_nested=True "
                "for a savepoint owned by the outer transaction"
            )
        with conn.raw.transaction():
            conn.execute(
                "SELECT pg_advisory_xact_lock(hashtext(current_database()), "
                "hashtext(current_schema() || ?))",
                (f":hermes.{self.store_name}",),
            )
            yield conn

    def initialize(self, conn, schema_sql, migrate):
        if conn.in_transaction:
            raise RuntimeError(
                f"{self.store_name.capitalize()} schema initialization requires its own transaction"
            )
        with self.write_txn(conn):
            conn.executescript(schema_sql)
            migrate(conn)


class KanbanPostgresCursor(_PostgresCursor):
    def _prepare(self, sql, *, returning):
        sql = sql.strip().rstrip(";")
        insert = _INSERT.match(sql)
        want_id = False
        if insert:
            mode, table = insert.groups()
            table = table.lower()
            dialect = self._conn.kanban_dialect
            dialect.check_table(table)
            if mode:
                sql = re.sub(
                    r"\bINSERT\s+OR\s+\w+", "INSERT", sql, count=1, flags=re.IGNORECASE
                )
                if re.search(r"\b(?:ON CONFLICT|RETURNING)\b", sql, re.IGNORECASE):
                    raise ValueError(
                        "SQLite conflict clauses cannot include a PG conflict clause"
                    )
                target = ", ".join(dialect.table_keys[table])
                sql += f" ON CONFLICT ({target}) DO "
                if mode.upper() == "IGNORE":
                    sql += "NOTHING"
                else:
                    columns = self._conn.kanban_dialect.table_info(self._conn, table)
                    updates = ", ".join(
                        f'"{column["name"]}" = EXCLUDED."{column["name"]}"'
                        for column in columns
                        if column["name"] not in dialect.table_keys[table]
                    )
                    sql += f"UPDATE SET {updates}" if updates else "NOTHING"
            want_id = (
                returning
                and table in dialect.identity_tables
                and not re.search(r"\bRETURNING\b", sql, re.IGNORECASE)
            )
            if want_id:
                sql += " RETURNING id"
        if re.match(r"(?:CREATE TABLE|ALTER TABLE)\b", sql, re.IGNORECASE):
            sql = _schema_statement(sql)
        return _translate_bindings(sql, null_safe=True), want_id

    def execute(self, sql, params=()):
        import psycopg

        translated, want_id = self._prepare(sql, returning=True)
        self.lastrowid = None
        try:
            self._cursor.execute(translated, params or ())
        except psycopg.IntegrityError as exc:
            raise sqlite3.IntegrityError(
                f"{self._conn.kanban_dialect.store_name.capitalize()} PostgreSQL constraint violation"
            ) from exc
        if want_id:
            row = self._cursor.fetchone()
            self.lastrowid = row[0] if row else None
        return self

    def executemany(self, sql, seq_of_params):
        import psycopg

        translated, _ = self._prepare(sql, returning=False)
        self.lastrowid = None
        try:
            self._cursor.executemany(translated, seq_of_params)
        except psycopg.IntegrityError as exc:
            raise sqlite3.IntegrityError(
                f"{self._conn.kanban_dialect.store_name.capitalize()} PostgreSQL constraint violation"
            ) from exc
        return self

    def executescript(self, sql_script):
        for statement in _split_sql_statements(sql_script):
            self.execute(statement)
        return self


class KanbanPostgresConnection(_PostgresConnection):
    """SQLite-shaped handle; lifetime and failed writes are never replayed."""

    kanban_dialect = PostgresDialect()

    @property
    def raw(self):
        return self._conn

    @property
    def in_transaction(self):
        from psycopg.pq import TransactionStatus

        return self.raw.info.transaction_status in (
            TransactionStatus.INTRANS,
            TransactionStatus.INERROR,
        )

    def cursor(self):
        return KanbanPostgresCursor(self.raw.cursor(), conn=self)

    def execute(self, sql, params=()):
        return self.cursor().execute(sql, params)

    def commit(self):
        self.raw.commit()

    def rollback(self):
        self.raw.rollback()

    def close(self):
        self.raw.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        if exc_type is not None:
            self.rollback()
        else:
            self.commit()


def open_postgres(
    schema_sql,
    migrate,
    *,
    dsn=None,
    env_var="HERMES_KANBAN_POSTGRES_DSN",
    connection_type=KanbanPostgresConnection,
):
    selected_dsn = dsn if dsn is not None else os.environ.get(env_var)
    if not selected_dsn or not selected_dsn.strip():
        store_name = connection_type.kanban_dialect.store_name
        raise ValueError(f"PostgreSQL {store_name} requires {env_var}")
    import psycopg

    conn = connection_type(
        psycopg.connect(
            selected_dsn, autocommit=True, connect_timeout=5, prepare_threshold=None
        )
    )
    try:
        conn.execute("SELECT set_config('lock_timeout', '5s', false)")
        conn.execute("SELECT set_config('statement_timeout', '30s', false)")
        conn.kanban_dialect.initialize(conn, schema_sql, migrate)
    except BaseException:
        conn.close()
        raise
    return conn
