"""PostgreSQL state schema, upgrades, and optional Telegram topic provisioning."""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from hermes_state_common import SCHEMA_SQL
from hermes_state_pg_triggers import POSTGRES_MESSAGE_TRIGGER_SQL
from hermes_state_schema import SessionSchemaMixin

logger = logging.getLogger(__name__)


_POSTGRES_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS schema_version (
    version INTEGER NOT NULL UNIQUE
);

-- Postgres-only migration ledger, deliberately SEPARATE from schema_version.
--
-- schema_version records the SHARED SCHEMA_VERSION, which advances with
-- upstream schema changes. The Postgres-only
-- migrations below have their own small counter that started at 17. Reading
-- both from one MAX(version) meant that as soon as the shared version passed
-- the highest pg-only version, every pg-only migration looked already-applied
-- and was skipped forever — the column-reconciler masked it for ADD COLUMN,
-- but indexes and CREATE TABLE silently never ran. The two counters are
-- unrelated and must not share a namespace.
CREATE TABLE IF NOT EXISTS pg_migration_version (
    version INTEGER NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    user_id TEXT,
    session_key TEXT,
    chat_id TEXT,
    chat_type TEXT,
    thread_id TEXT,
    display_name TEXT,
    origin_json TEXT,
    expiry_finalized INTEGER DEFAULT 0,
    model TEXT,
    model_config TEXT,
    system_prompt TEXT,
    parent_session_id TEXT,
    started_at DOUBLE PRECISION NOT NULL,
    ended_at DOUBLE PRECISION,
    end_reason TEXT,
    message_count INTEGER DEFAULT 0,
    tool_call_count INTEGER DEFAULT 0,
    input_tokens INTEGER DEFAULT 0,
    output_tokens INTEGER DEFAULT 0,
    cache_read_tokens INTEGER DEFAULT 0,
    cache_write_tokens INTEGER DEFAULT 0,
    reasoning_tokens INTEGER DEFAULT 0,
    cwd TEXT,
    git_branch TEXT,
    git_repo_root TEXT,
    billing_provider TEXT,
    billing_base_url TEXT,
    billing_mode TEXT,
    estimated_cost_usd DOUBLE PRECISION,
    actual_cost_usd DOUBLE PRECISION,
    cost_status TEXT,
    cost_source TEXT,
    pricing_version TEXT,
    title TEXT,
    title_source TEXT,
    api_call_count INTEGER DEFAULT 0,
    handoff_state TEXT,
    handoff_platform TEXT,
    handoff_error TEXT,
    compression_failure_cooldown_until DOUBLE PRECISION,
    compression_failure_error TEXT,
    compression_recovery_deadline DOUBLE PRECISION,
    compression_fallback_streak INTEGER NOT NULL DEFAULT 0,
    profile_name TEXT,
    rewind_count INTEGER NOT NULL DEFAULT 0,
    archived INTEGER NOT NULL DEFAULT 0,
    system_prompt_hash TEXT,
    last_activity_at DOUBLE PRECISION,
    last_activity_description TEXT,
    last_activity_provenance TEXT,
    compression_ineffective_count INTEGER NOT NULL DEFAULT 0,
    pinned INTEGER NOT NULL DEFAULT 0,
    last_read_at DOUBLE PRECISION,
    git_metadata_generation INTEGER NOT NULL DEFAULT 0,
    hidden INTEGER NOT NULL DEFAULT 0,
    tool_names TEXT,
    FOREIGN KEY (parent_session_id) REFERENCES sessions(id)
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(id),
    role TEXT NOT NULL,
    content TEXT,
    tool_call_id TEXT,
    tool_calls TEXT,
    tool_name TEXT,
    effect_disposition TEXT,
    timestamp DOUBLE PRECISION NOT NULL,
    token_count INTEGER,
    finish_reason TEXT,
    reasoning TEXT,
    reasoning_content TEXT,
    reasoning_details TEXT,
    codex_reasoning_items TEXT,
    codex_message_items TEXT,
    platform_message_id TEXT,
    observed INTEGER DEFAULT 0,
    -- Mirrors the levos display_only column in SCHEMA_SQL: transcript-only
    -- rows that context reconstruction must skip. Declared here AND in the
    -- v25 migration so fresh and converged databases have the same shape.
    display_only INTEGER DEFAULT 0,
    _compressed_summary INTEGER NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1,
    compacted INTEGER NOT NULL DEFAULT 0,
    api_content TEXT,
    display_kind TEXT,
    display_metadata TEXT,
    display_identity BYTEA,
    display_order INTEGER,
    -- PostgreSQL-only: no SQLite counterpart (tsvector has no SQLite type).
    -- Declared here as well as in the v19 migration so a FRESH database has
    -- the same shape as a converged one. Without this, fresh databases never
    -- get the column at all — see the note on migration skipping in
    -- init_postgres_schema.
    fts_content tsvector
);

-- Derived manifest: canonical messages remain lossless while oversized search
-- documents are indexed from a bounded UTF-8 prefix. This table is not part of
-- SQLite authority or dual-write; it is rebuilt/maintained with fts_content.
CREATE TABLE IF NOT EXISTS hermes_fts_truncations (
    message_id BIGINT PRIMARY KEY REFERENCES messages(id) ON DELETE CASCADE,
    source_bytes BIGINT NOT NULL,
    indexed_bytes BIGINT NOT NULL,
    recorded_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS system_prompts (
    hash TEXT PRIMARY KEY,
    prompt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS session_model_usage (
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    model TEXT NOT NULL,
    billing_provider TEXT NOT NULL DEFAULT '',
    billing_base_url TEXT NOT NULL DEFAULT '',
    billing_mode TEXT NOT NULL DEFAULT '',
    task TEXT NOT NULL DEFAULT '',
    api_call_count INTEGER NOT NULL DEFAULT 0,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    cache_read_tokens INTEGER NOT NULL DEFAULT 0,
    cache_write_tokens INTEGER NOT NULL DEFAULT 0,
    reasoning_tokens INTEGER NOT NULL DEFAULT 0,
    estimated_cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
    actual_cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
    cost_status TEXT,
    cost_source TEXT,
    first_seen DOUBLE PRECISION,
    last_seen DOUBLE PRECISION,
    PRIMARY KEY (session_id, model, billing_provider, billing_base_url, billing_mode, task)
);

CREATE TABLE IF NOT EXISTS state_meta (
    key TEXT PRIMARY KEY,
    value TEXT
);

CREATE TABLE IF NOT EXISTS gateway_routing (
    scope TEXT NOT NULL DEFAULT '',
    session_key TEXT NOT NULL,
    entry_json TEXT NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (scope, session_key)
);

CREATE TABLE IF NOT EXISTS compression_locks (
    session_id TEXT PRIMARY KEY,
    holder TEXT NOT NULL,
    acquired_at DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS session_turn_leases (
    conversation_id TEXT PRIMARY KEY,
    holder TEXT NOT NULL,
    acquired_at DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL,
    lease_epoch INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS gateway_hygiene_state (
    session_key TEXT PRIMARY KEY,
    failure_streak INTEGER NOT NULL DEFAULT 0
);

-- PG3 also carries the state.db ledgers whose current owners connect to SQLite
-- directly.  Declaring them here makes fresh and already-initialized writable
-- PostgreSQL stores converge when this base schema is replayed.  Their writers
-- must still move behind SessionDB before a live dual-write window can cover
-- new mutations; schema/COPY parity alone cannot observe a bypass writer.
CREATE TABLE IF NOT EXISTS levos_control_tower_event (
    event_id TEXT PRIMARY KEY,
    kind TEXT NOT NULL,
    payload_text TEXT NOT NULL DEFAULT '',
    origin_session_id TEXT,
    created_at DOUBLE PRECISION NOT NULL,
    interval_open INTEGER NOT NULL DEFAULT 0 CHECK (interval_open IN (0, 1)),
    responded_at DOUBLE PRECISION,
    consumed_at DOUBLE PRECISION,
    consumed_by_session_id TEXT
);

CREATE TABLE IF NOT EXISTS levos_control_tower_delivery (
    event_id TEXT NOT NULL,
    attempt_no INTEGER NOT NULL,
    session_id TEXT NOT NULL,
    claimed_at DOUBLE PRECISION NOT NULL,
    injected_at DOUBLE PRECISION,
    inject_ok INTEGER NOT NULL DEFAULT 0 CHECK (inject_ok IN (0, 1)),
    responded_at DOUBLE PRECISION,
    PRIMARY KEY (event_id, attempt_no),
    UNIQUE (event_id, session_id),
    FOREIGN KEY (event_id) REFERENCES levos_control_tower_event(event_id)
);

CREATE TABLE IF NOT EXISTS levos_control_tower_role (
    role TEXT PRIMARY KEY CHECK (role = 'control_tower'),
    session_id TEXT NOT NULL,
    source TEXT NOT NULL,
    assigned_at DOUBLE PRECISION NOT NULL,
    last_event_id TEXT
);

CREATE TABLE IF NOT EXISTS levos_control_tower_forward (
    forward_key TEXT PRIMARY KEY,
    event_id TEXT NOT NULL,
    control_session_id TEXT NOT NULL,
    target_session_id TEXT NOT NULL,
    text_sha256 TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    delivered_at DOUBLE PRECISION,
    FOREIGN KEY (event_id) REFERENCES levos_control_tower_event(event_id)
);

CREATE TABLE IF NOT EXISTS async_delegations (
    delegation_id TEXT PRIMARY KEY,
    origin_session TEXT NOT NULL,
    origin_ui_session_id TEXT NOT NULL DEFAULT '',
    parent_session_id TEXT,
    state TEXT NOT NULL,
    dispatched_at DOUBLE PRECISION NOT NULL,
    completed_at DOUBLE PRECISION,
    updated_at DOUBLE PRECISION NOT NULL,
    event_json TEXT,
    result_json TEXT,
    delivery_state TEXT NOT NULL DEFAULT 'pending',
    delivery_attempts INTEGER NOT NULL DEFAULT 0,
    delivered_at DOUBLE PRECISION,
    owner_pid INTEGER,
    owner_started_at INTEGER,
    task_json TEXT,
    delivery_claim TEXT,
    delivery_claimed_at DOUBLE PRECISION,
    origin_session_id TEXT
);

CREATE TABLE IF NOT EXISTS delivery_obligations (
    obligation_id TEXT PRIMARY KEY,
    session_key TEXT NOT NULL,
    platform TEXT NOT NULL,
    chat_id TEXT NOT NULL,
    thread_id TEXT,
    content TEXT NOT NULL,
    state TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    owner_pid INTEGER,
    owner_started_at INTEGER,
    last_error TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_levos_control_empty_open
    ON levos_control_tower_event(kind)
    WHERE kind = 'empty_epoch' AND interval_open = 1;
CREATE INDEX IF NOT EXISTS idx_async_delegations_delivery
    ON async_delegations(delivery_state, completed_at);

CREATE TABLE IF NOT EXISTS conversation_generations (
    source TEXT NOT NULL,
    session_key TEXT NOT NULL,
    generation INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (source, session_key)
);

CREATE TABLE IF NOT EXISTS gateway_heartbeats (
    backend_id TEXT PRIMARY KEY,
    pid INTEGER NOT NULL,
    started_at DOUBLE PRECISION NOT NULL,
    last_heartbeat DOUBLE PRECISION NOT NULL,
    profile TEXT NOT NULL DEFAULT '',
    host TEXT NOT NULL DEFAULT ''
);

"""

# Run only after column reconciliation: legacy tables can lack indexed columns.
_POSTGRES_INDEX_SQL = """
CREATE INDEX IF NOT EXISTS idx_session_turn_leases_expires ON session_turn_leases(expires_at);

CREATE INDEX IF NOT EXISTS idx_sessions_source ON sessions(source);
CREATE INDEX IF NOT EXISTS idx_sessions_source_id ON sessions(source, id);
CREATE INDEX IF NOT EXISTS idx_sessions_parent ON sessions(parent_session_id);
CREATE INDEX IF NOT EXISTS idx_sessions_started ON sessions(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_session ON messages(session_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_messages_session_active
    ON messages(session_id, active, timestamp);
CREATE INDEX IF NOT EXISTS idx_compression_locks_expires
    ON compression_locks(expires_at);
CREATE INDEX IF NOT EXISTS idx_session_model_usage_session
    ON session_model_usage(session_id);
CREATE INDEX IF NOT EXISTS idx_session_model_usage_model
    ON session_model_usage(model);
CREATE INDEX IF NOT EXISTS idx_messages_session_id ON messages(session_id, id);
CREATE INDEX IF NOT EXISTS idx_messages_assistant_calls_by_session
    ON messages(session_id) WHERE role = 'assistant' AND tool_calls IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_messages_display_page
    ON messages(session_id, display_order, active DESC, id DESC)
    WHERE active = 1 OR compacted = 1;
CREATE INDEX IF NOT EXISTS idx_messages_display_backfill
    ON messages(session_id) WHERE (display_order IS NULL OR display_identity IS NULL)
    AND (active = 1 OR compacted = 1);
CREATE INDEX IF NOT EXISTS idx_messages_display_identity
    ON messages(session_id, display_identity, display_order)
    WHERE display_identity IS NOT NULL AND (active = 1 OR compacted = 1);
CREATE INDEX IF NOT EXISTS idx_messages_active_null ON messages(active) WHERE active IS NULL;
-- Completeness is checked per search because other writers can add NULL vectors.
CREATE INDEX IF NOT EXISTS idx_messages_fts_pending ON messages(id) WHERE fts_content IS NULL;
CREATE INDEX IF NOT EXISTS idx_sessions_session_key ON sessions(session_key, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_gateway_peer
    ON sessions(source, user_id, chat_id, chat_type, thread_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_handoff_state ON sessions(handoff_state, started_at);
CREATE INDEX IF NOT EXISTS idx_sessions_system_prompt_hash ON sessions(system_prompt_hash);
CREATE INDEX IF NOT EXISTS idx_sessions_effective_activity
    ON sessions(COALESCE(last_activity_at, started_at) DESC, started_at DESC);
"""

SCHEMA_SQL_POSTGRES = _POSTGRES_TABLE_SQL + _POSTGRES_INDEX_SQL


@dataclass(frozen=True)
class PostgresMigration:
    """A single Postgres-only schema migration step.

    ``version``: Postgres-local version number. This is its own sequence,
        tracked in ``pg_migration_version`` — unrelated to, and NOT comparable
        with, the shared SCHEMA_VERSION.
    ``sql``: DDL to execute. Each ``;``-separated statement runs independently
        in autocommit mode via the raw psycopg connection (not the adapter),
        so SQLite-compat translation is bypassed. Do NOT embed ``;`` inside
        dollar-quoted (``$$``) blocks or single-quoted literals — the split
        is naive.
    ``raw_statements``: Additional intact PostgreSQL statements, executed
        after ``sql`` without splitting procedural function bodies.
    ``optional``: If ``True``, any exception is logged at WARNING and the
        migration is skipped without recording the version (enabling retry on
        next connect). If ``False``, the exception propagates.
    """

    version: int
    sql: str
    optional: bool = False
    raw_statements: tuple[str, ...] = ()


_PG_ONLY_MIGRATIONS: List[PostgresMigration] = [
    # v17 — Install pg_trgm, which accelerates the ILIKE search path via the
    # GIN indexes in v18. A no-op where the extension is already installed.
    #
    # optional=True because pg_trgm is an OPTIMIZATION, not a requirement:
    # ILIKE is plain SQL and the tsvector FTS path (v19) is core PostgreSQL, so
    # search is correct without the extension — only slower on large tables.
    # Making this fatal would be strictly worse than the degradation it
    # prevents.
    #
    # This is not hypothetical. Managed providers restrict which extensions a
    # non-superuser may create, and some ship with an empty allow-list by
    # default: creating pg_trgm then fails with a permission or
    # FeatureNotSupported error that no amount of retrying will clear. With
    # optional=False that error propagated out of init_postgres_schema and
    # SessionDB.__init__, so the agent could not start at all against an
    # otherwise perfectly healthy database. Verified against Azure Database for
    # PostgreSQL Flexible Server 18.4, whose default azure.extensions parameter
    # is empty.
    #
    # The failure is logged at WARNING and the version is not recorded, so the
    # migration retries on the next connect and picks the extension up
    # automatically if an operator later allow-lists it.
    PostgresMigration(
        version=17,
        optional=True,
        sql="CREATE EXTENSION IF NOT EXISTS pg_trgm",
    ),
    # v18 — GIN trigram indexes on the three searched columns. optional=True
    # because index builds can fail transiently (lock, OOM, disk full) and
    # because they cannot be built at all when v17 could not install pg_trgm;
    # ILIKE still works without them (just slower). IF NOT EXISTS makes this
    # idempotent so pre-created indexes on large production tables are skipped.
    PostgresMigration(
        version=18,
        optional=True,
        sql=(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_messages_content_trgm"
            "    ON messages USING GIN (content gin_trgm_ops);\n"
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_messages_tool_name_trgm"
            "    ON messages USING GIN (tool_name gin_trgm_ops);\n"
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_messages_tool_calls_trgm"
            "    ON messages USING GIN (tool_calls gin_trgm_ops)"
        ),
    ),
    # v19 — Native FTS column for tokenized AND-search (parity with SQLite FTS5).
    # ADD COLUMN with no DEFAULT is a metadata-only change on PG 11+ — no table
    # rewrite, no ACCESS EXCLUSIVE lock beyond milliseconds. The GIN index build
    # is CONCURRENTLY (non-blocking). NEW rows are populated by the per-INSERT
    # hook (_update_fts_content); EXISTING rows stay fts_content IS NULL until
    # the operator runs the one-time backfill UPDATE (documented in the
    # PostgreSQL backend guide under website/docs/user-guide/features/).
    # Until backfill completes, search stays on the ILIKE
    # path (which covers all rows) — see _fts_backfill_complete. optional=True so
    # a transient CONCURRENTLY failure retries next connect without hard-failing
    # startup. Uses 'simple' dictionary (lowercase only, no stemming) — correct
    # for a multilingual corpus with code identifiers, proper nouns, and names.
    PostgresMigration(
        version=19,
        optional=True,
        sql=(
            "ALTER TABLE messages"
            " ADD COLUMN IF NOT EXISTS fts_content tsvector;\n"
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_messages_fts_gin"
            "    ON messages USING GIN (fts_content)"
        ),
    ),
    # v20 — Sync sessions + messages columns to upstream SCHEMA_VERSION=19.
    # Sessions gained: session_key, chat_id, chat_type, thread_id,
    #   display_name, origin_json, expiry_finalized, git_branch, git_repo_root,
    #   compression_failure_cooldown_until, compression_failure_error.
    # Messages gained: compacted.
    # All ADD COLUMN IF NOT EXISTS — idempotent on fresh installs where
    # SCHEMA_SQL_POSTGRES already has these columns. optional=True so a
    # transient failure retries on the next connect without hard-failing boot.
    PostgresMigration(
        version=20,
        optional=True,
        sql=(
            # Add unique constraint to schema_version so ON CONFLICT DO NOTHING
            # works correctly for future version inserts. CREATE UNIQUE INDEX is
            # used instead of ALTER TABLE ADD CONSTRAINT because the latter
            # requires an explicit constraint name and is more verbose; both are
            # equivalent for this purpose.
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_schema_version_unique"
            "    ON schema_version(version);\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS session_key TEXT;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS chat_id TEXT;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS chat_type TEXT;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS thread_id TEXT;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS display_name TEXT;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS origin_json TEXT;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS expiry_finalized INTEGER DEFAULT 0;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS git_branch TEXT;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS git_repo_root TEXT;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS compression_failure_cooldown_until DOUBLE PRECISION;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS compression_failure_error TEXT;\n"
            "ALTER TABLE messages ADD COLUMN IF NOT EXISTS compacted INTEGER NOT NULL DEFAULT 0;\n"
            "CREATE INDEX IF NOT EXISTS idx_sessions_session_key"
            "    ON sessions(session_key, started_at DESC);\n"
            "CREATE INDEX IF NOT EXISTS idx_sessions_gateway_peer"
            "    ON sessions(source, user_id, chat_id, chat_type, thread_id, started_at DESC);\n"
            "CREATE INDEX IF NOT EXISTS idx_sessions_handoff_state"
            "    ON sessions(handoff_state, started_at)"
        ),
    ),
    # v21 — Converge the four columns + one table that drifted after v20.
    #
    # Root cause of the drift: SCHEMA_SQL_POSTGRES was hand-maintained against
    # hermes_state_common.SCHEMA_SQL, so every upstream column addition landed on
    # SQLite (self-healing via _reconcile_columns) and silently NOT on
    # Postgres. Symptom was deployment-wide transcript loss logged only at WARNING:
    #   column "profile_name" of relation "sessions" does not exist
    #   column "effect_disposition" of relation "messages" does not exist
    #
    # ``session_model_usage`` was missing entirely, not merely short a column.
    # It did not appear in the error logs because session creation failed
    # first — fixing only the columns would have unmasked a missing-relation
    # error on every ``update_token_counts`` call instead.
    #
    # At v21 ``async_delegations`` was deliberately absent because its writer
    # bypassed SessionDB. PG3 X1a later classified it as an upstream schema
    # omission and put it in the replayed base schema; the historical v21 SQL
    # stays unchanged. ``reconcile_postgres_columns`` (below) still only ADDs
    # columns to tables that already exist, never CREATEs tables.
    #
    # optional=True matches its siblings: a transient failure retries on the
    # next connect rather than hard-failing boot.
    PostgresMigration(
        version=21,
        optional=True,
        sql=(
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS"
            "    compression_fallback_streak INTEGER NOT NULL DEFAULT 0;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS profile_name TEXT;\n"
            "ALTER TABLE messages ADD COLUMN IF NOT EXISTS effect_disposition TEXT;\n"
            "ALTER TABLE messages ADD COLUMN IF NOT EXISTS api_content TEXT;\n"
            "CREATE TABLE IF NOT EXISTS session_model_usage ("
            "    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,"
            "    model TEXT NOT NULL,"
            "    billing_provider TEXT NOT NULL DEFAULT '',"
            "    billing_base_url TEXT NOT NULL DEFAULT '',"
            "    billing_mode TEXT NOT NULL DEFAULT '',"
            "    task TEXT NOT NULL DEFAULT '',"
            "    api_call_count INTEGER NOT NULL DEFAULT 0,"
            "    input_tokens INTEGER NOT NULL DEFAULT 0,"
            "    output_tokens INTEGER NOT NULL DEFAULT 0,"
            "    cache_read_tokens INTEGER NOT NULL DEFAULT 0,"
            "    cache_write_tokens INTEGER NOT NULL DEFAULT 0,"
            "    reasoning_tokens INTEGER NOT NULL DEFAULT 0,"
            "    estimated_cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0,"
            "    actual_cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0,"
            "    cost_status TEXT,"
            "    cost_source TEXT,"
            "    first_seen DOUBLE PRECISION,"
            "    last_seen DOUBLE PRECISION,"
            "    PRIMARY KEY (session_id, model, billing_provider,"
            "                 billing_base_url, billing_mode, task)"
            ");\n"
            "CREATE INDEX IF NOT EXISTS idx_session_model_usage_session"
            "    ON session_model_usage(session_id);\n"
            "CREATE INDEX IF NOT EXISTS idx_session_model_usage_model"
            "    ON session_model_usage(model)"
        ),
    ),
    # v22 — Sync sessions + messages to upstream v0.20 (tag v2026.8.3).
    #
    # Upstream added six sessions columns, two messages columns, and the
    # system_prompts table to SCHEMA_SQL. Caught by tests/test_pg_schema_parity
    # during a later upstream merge — i.e. the parity guard doing its job before
    # the drift reached a live database, rather than after (cf. the earlier
    # incident, where every session-transcript write failed silently for weeks).
    #
    # reconcile_postgres_columns() would ADD the columns on a live database at
    # runtime, but it deliberately never CREATEs tables, so system_prompts
    # needs this migration to exist at all.
    PostgresMigration(
        version=22,
        optional=True,
        sql=(
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS system_prompt_hash TEXT;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS"
            "    last_activity_at DOUBLE PRECISION;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS"
            "    last_activity_description TEXT;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS"
            "    last_activity_provenance TEXT;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS"
            "    compression_ineffective_count INTEGER NOT NULL DEFAULT 0;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS"
            "    pinned INTEGER NOT NULL DEFAULT 0;\n"
            "ALTER TABLE messages ADD COLUMN IF NOT EXISTS display_kind TEXT;\n"
            "ALTER TABLE messages ADD COLUMN IF NOT EXISTS display_metadata TEXT;\n"
            "CREATE TABLE IF NOT EXISTS system_prompts ("
            "    hash TEXT PRIMARY KEY,"
            "    prompt TEXT NOT NULL"
            ")"
        ),
    ),
    # v23 — Sync sessions to upstream v0.20.1 (tag v2026.8.13).
    #
    # Upstream added two sessions columns (title_source, last_read_at) to
    # SCHEMA_SQL between v2026.8.3 and v2026.8.13. Caught by
    # tests/test_pg_schema_parity during that merge — the parity guard
    # doing its job again, same as it did for v22.
    #
    # No new tables this time, so reconcile_postgres_columns() would in fact
    # heal a live database on its own. This migration exists anyway for the
    # same reason v22 does: the declaration in SCHEMA_SQL_POSTGRES plus a
    # numbered migration is the documented contract, and relying on the
    # runtime backstop alone leaves a fresh database dependent on it.
    PostgresMigration(
        version=23,
        optional=True,
        sql=(
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS title_source TEXT;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS"
            "    last_read_at DOUBLE PRECISION"
        ),
    ),
    # v24 — Sync to upstream's session_turn_leases table and the two sessions
    # columns that accompany it (git_metadata_generation, hidden).
    #
    # Unlike v23 this one is NOT covered by the runtime backstop on its own:
    # reconcile_postgres_columns() ADDs missing columns but deliberately never
    # CREATEs tables, so session_turn_leases needs an explicit migration or a
    # live database never gets it. The two sessions columns would self-heal,
    # but they belong to the same upstream change and ship together here so
    # the declaration and the migration stay in step.
    #
    # ADD COLUMN IF NOT EXISTS / CREATE TABLE IF NOT EXISTS keep this
    # idempotent, so a partially-applied run is safe to retry.
    PostgresMigration(
        version=24,
        optional=True,
        sql=(
            "CREATE TABLE IF NOT EXISTS session_turn_leases (\n"
            "    conversation_id TEXT PRIMARY KEY,\n"
            "    holder TEXT NOT NULL,\n"
            "    acquired_at DOUBLE PRECISION NOT NULL,\n"
            "    expires_at DOUBLE PRECISION NOT NULL\n"
            ");\n"
            "CREATE INDEX IF NOT EXISTS idx_session_turn_leases_expires\n"
            "    ON session_turn_leases(expires_at);\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS\n"
            "    git_metadata_generation INTEGER NOT NULL DEFAULT 0;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS\n"
            "    hidden INTEGER NOT NULL DEFAULT 0"
        ),
    ),
    # v25 — gateway_hygiene_state, added upstream to SCHEMA_SQL. The table is
    # read and written by SessionDB on the shared (backend-agnostic) path, so
    # a Postgres-backed install needs it too. Caught by the schema-parity guard
    # rather than by anyone noticing — which is the guard doing its job.
    #
    # reconcile_postgres_columns only ever ADDs columns, never CREATEs tables,
    # so this needs an explicit migration or a live database never gets it.
    PostgresMigration(
        version=25,
        optional=True,
        sql=(
            "CREATE TABLE IF NOT EXISTS gateway_hygiene_state (\n"
            "    session_key TEXT PRIMARY KEY,\n"
            "    failure_streak INTEGER NOT NULL DEFAULT 0\n"
            ");\n"
            # messages.display_only rides the same version (levos session-plane
            # hotfix): the shared read path filters on it, so a Postgres database
            # converged before the fork carried the column would otherwise fail
            # the schema-parity guard. ADD COLUMN IF NOT EXISTS is idempotent.
            "ALTER TABLE messages ADD COLUMN IF NOT EXISTS display_only INTEGER DEFAULT 0;\n"
            # session_turn_leases.lease_epoch (levos S1 fencing token) rides here too:
            # the pg-only range must stay below the shared SCHEMA_VERSION, so no new
            # entry. A database that recorded v25 before this column existed is healed
            # on its next writable connect by reconcile_postgres_columns().
            "ALTER TABLE session_turn_leases ADD COLUMN IF NOT EXISTS\n"
            "    lease_epoch INTEGER NOT NULL DEFAULT 0"
        ),
    ),
    # Required state used by current conversation boundaries, liveness and
    # transcript/display reads. Optional extension/index optimizations above
    # may fail independently; a missing durable state field must stop startup.
    PostgresMigration(
        version=26,
        sql=(
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS compression_recovery_deadline DOUBLE PRECISION;\n"
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS tool_names TEXT;\n"
            "ALTER TABLE messages ADD COLUMN IF NOT EXISTS _compressed_summary INTEGER NOT NULL DEFAULT 0;\n"
            "ALTER TABLE messages ADD COLUMN IF NOT EXISTS display_identity BYTEA;\n"
            "ALTER TABLE messages ADD COLUMN IF NOT EXISTS display_order INTEGER;\n"
            # v19 may have been skipped or recorded on a drifted store. The
            # pending-vector index requires the column even without GIN.
            "ALTER TABLE messages ADD COLUMN IF NOT EXISTS fts_content tsvector;\n"
            "CREATE TABLE IF NOT EXISTS conversation_generations ("
            "source TEXT NOT NULL, session_key TEXT NOT NULL, generation INTEGER NOT NULL DEFAULT 0, "
            "PRIMARY KEY (source, session_key));\n"
            "CREATE TABLE IF NOT EXISTS gateway_heartbeats ("
            "backend_id TEXT PRIMARY KEY, pid INTEGER NOT NULL, started_at DOUBLE PRECISION NOT NULL, "
            "last_heartbeat DOUBLE PRECISION NOT NULL, profile TEXT NOT NULL DEFAULT '', host TEXT NOT NULL DEFAULT '');\n"
            + _POSTGRES_INDEX_SQL
        ),
    ),
    # Pre-trigger stores can contain stale non-NULL vectors and identities.
    # Invalidate them once before recording the required projection contract;
    # read-only opens must not serve those stores until this migration runs.
    PostgresMigration(
        version=27,
        sql="",
        raw_statements=(
            *POSTGRES_MESSAGE_TRIGGER_SQL,
            "UPDATE messages SET display_identity = NULL, display_order = NULL, fts_content = NULL",
        ),
    ),
]


def plan_postgres_migrations(
    current_version: int,
    applied: Optional[set] = None,
) -> List[PostgresMigration]:
    """Return pending Postgres-only migrations.

    *current_version* is the high-water mark from ``pg_migration_version``
    ``MAX(version)`` — NOT the shared ``SCHEMA_VERSION`` constant, which
    governs only the SQLite/shared schema.

    *applied* is the full set of recorded versions. It matters because an
    ``optional=True`` migration that fails does NOT record its version, while
    later migrations still succeed and do. A pure ``> MAX(version)`` rule would
    then strand the skipped one forever: pg_trgm denied by a managed provider's
    extension allow-list would never be retried even after an operator
    allow-lists it, because v19+ already pushed the high-water mark past it.

    Passing *applied* replays any gap below the high-water mark. Recorded
    migrations are skipped. Pending migrations must tolerate replay after a
    partial failure: conditional DDL and replaceable trigger definitions do,
    while projection repairs may invalidate cached fields again. Retrying a
    still-failing optional migration logs a warning on each connection.
    """
    if applied is None:
        return [m for m in _PG_ONLY_MIGRATIONS if m.version > current_version]
    return [
        m
        for m in _PG_ONLY_MIGRATIONS
        if m.version > current_version or m.version not in applied
    ]


def _probe_pg_trgm(conn: Any) -> bool:
    """Return ``True`` if pg_trgm is installed in the current database.

    TEST UTILITY — not called from the production path. Uses a catalog probe
    rather than ``try/except`` on DDL to avoid putting the psycopg connection
    into an aborted-transaction state.
    """
    try:
        row = conn.execute(
            "SELECT 1 FROM pg_catalog.pg_extension WHERE extname = 'pg_trgm'"
        ).fetchone()
        return row is not None
    except Exception:
        return False


def postgres_applied_migrations(conn: Any) -> set:
    """Return the set of recorded Postgres-only migration versions.

    Distinct from :func:`postgres_migration_version`, which returns only the
    maximum. The full set is what lets the planner spot a GAP — an optional
    migration that failed while later ones succeeded — and retry it instead of
    stranding it below the high-water mark.
    """
    try:
        rows = conn.execute("SELECT version FROM pg_migration_version").fetchall()
    except Exception:
        return set()
    return {
        int(r["version"]) for r in (rows or []) if r["version"] is not None
    }


def _apply_single_migration(conn: Any, migration: PostgresMigration) -> None:
    """Execute one migration's SQL and record the version.

    Executes against ``conn.raw`` (raw psycopg), NOT the ``_PostgresCursor``
    adapter, so migration DDL is not subject to SQLite-compat translation
    (``?`` → ``%s``, strict-mode checks, etc.).

    ``CREATE INDEX CONCURRENTLY`` requires the connection to be in autocommit
    mode. ``connect_postgres`` always opens with ``autocommit=True``, so each
    statement commits immediately — this is correct and required for
    CONCURRENTLY.

    The version INSERT runs last. If a prior statement fails the version is not
    recorded, so the migration retries on the next connect.
    """
    raw = conn.raw if hasattr(conn, "raw") else conn
    for statement in (*_schema_statements(migration.sql), *migration.raw_statements):
        if "INDEX" in statement.upper():
            logger.info(
                "pg-only migration v%d: creating index (may take a while"
                " on large tables): %.80s…",
                migration.version,
                statement,
            )
        raw.execute(statement)
    # Append-only version record. ON CONFLICT DO NOTHING makes a concurrent
    # second runner safe (both see version N, both try to insert — second wins
    # the race but the INSERT is a harmless no-op).
    raw.execute(
        "INSERT INTO pg_migration_version (version) VALUES (%s) ON CONFLICT DO NOTHING",
        (migration.version,),
    )


def apply_postgres_migrations(conn: Any) -> None:
    """Apply any pending Postgres-only migrations.

    Called by :func:`init_postgres_schema` on every connect. Reads the recorded
    versions from ``pg_migration_version`` and applies anything not yet
    recorded — including gaps below the high-water mark, so an optional
    migration that failed earlier is retried rather than stranded. Completed
    migrations do not run again; unfinished DDL and data repairs must be safe
    to replay.

    The version ``INSERT … ON CONFLICT DO NOTHING`` tolerates duplicate ledger
    writes. It does not serialize concurrent initializers' DDL, which can
    still require a retry if they race to create the same objects.

    Optional migrations (``optional=True``) log a WARNING on failure without
    recording the version, enabling retry on next connect. Non-optional
    migrations propagate the exception.
    """
    current = postgres_migration_version(conn)
    applied = postgres_applied_migrations(conn)
    pending = plan_postgres_migrations(current, applied)
    if not pending:
        return
    for migration in pending:
        if migration.optional:
            try:
                _apply_single_migration(conn, migration)
                logger.info("pg-only migration v%d applied", migration.version)
            except Exception as exc:
                logger.warning(
                    "pg-only migration v%d skipped (optional): %s",
                    migration.version,
                    exc,
                )
        else:
            _apply_single_migration(conn, migration)
            logger.info("pg-only migration v%d applied", migration.version)


def _schema_statements(sql: str):
    # These declarative scripts contain no procedural bodies or quoted
    # semicolons. Strip comments before splitting so comment prose cannot
    # accidentally become an executable statement.
    for statement in re.sub(r"--[^\n]*", "", sql).split(";"):
        if statement.strip():
            yield statement.strip()


def init_postgres_schema(
    conn: Any, schema_version: int, *, defer_indexes: bool = False
) -> None:
    """Provision tables, require column parity, then build indexes and record success.

    ``defer_indexes=True`` (online COPY backfill) provisions tables and records
    the version only; secondary indexes and Postgres-only migrations are built
    afterwards by :func:`finalize_postgres_schema`. Primary-key/unique indexes
    remain part of CREATE TABLE because they are required for
    conflict-idempotent batches.

    CREATE TABLE IF NOT EXISTS leaves existing tables untouched. Indexes must
    wait for reconciliation, or an index on a newly added column prevents the
    upgrade that would have supplied that column. Required DDL failures
    propagate; callers must never serve a partially usable state store.
    """
    raw = conn.raw if hasattr(conn, "raw") else conn
    for statement in _schema_statements(_POSTGRES_TABLE_SQL):
        raw.execute(statement)
    reconcile_postgres_columns(conn, SCHEMA_SQL)
    if not defer_indexes:
        apply_postgres_migrations(conn)
        for statement in _schema_statements(_POSTGRES_INDEX_SQL):
            raw.execute(statement)
    # Keep the shared version separate from the PostgreSQL migration ledger,
    # and never claim completion before the required schema work succeeds.
    if postgres_schema_version(conn) < schema_version:
        raw.execute(
            "INSERT INTO schema_version (version) VALUES (%s) ON CONFLICT DO NOTHING", (schema_version,)
        )
    conn.commit()


def finalize_postgres_schema(conn: Any) -> None:
    """Build deferred base/GIN indexes after a bulk COPY has completed."""
    raw = conn.raw if hasattr(conn, "raw") else conn
    reconcile_postgres_columns(conn, SCHEMA_SQL)
    apply_postgres_migrations(conn)
    for statement in _schema_statements(_POSTGRES_INDEX_SQL):
        raw.execute(statement)
    conn.commit()


def postgres_schema_version(conn: Any) -> int:
    """Return the recorded schema version, or 0 if the schema is uninitialized."""
    try:
        row = conn.execute("SELECT MAX(version) AS version FROM schema_version").fetchone()
    except Exception:
        return 0
    if not row or row["version"] is None:
        return 0
    return int(row["version"])


def postgres_migration_version(conn: Any) -> int:
    """Return the highest applied Postgres-only migration version, else 0.

    Read from ``pg_migration_version``, which is separate from the shared
    ``schema_version`` on purpose — see the note on the table in
    SCHEMA_SQL_POSTGRES.

    Databases created before that split have no ``pg_migration_version`` row
    and fall back to 0, which replans every Postgres-only migration from the
    start. That is deliberate, and it is a repair rather than a cost:

    * Migrations use conditional DDL or replaceable definitions to preserve
      existing objects while repairing their contract. Projection repairs can
      invalidate cached fields; their ledger record prevents repeating that
      work on later connections.
    * A legacy database's ledger cannot be trusted anyway. While pg-only
      versions shared the ``schema_version`` namespace, a shared version above
      the pg-only range made every migration look applied, so they were
      skipped — and some databases carry *recorded* versions whose objects were
      never created. ``reconcile_postgres_columns`` heals missing columns but
      never creates extensions, indexes, or tables, so a trusted-but-wrong
      ledger would leave those missing permanently (no pg_trgm, no search
      indexes) with nothing to ever repair them.

    Replanning from 0 converges both cases on the same correct end state.
    """
    try:
        row = conn.execute(
            "SELECT MAX(version) AS version FROM pg_migration_version"
        ).fetchone()
    except Exception:
        return 0
    if not row or row["version"] is None:
        return 0
    return int(row["version"])


# ---------------------------------------------------------------------------
# Declarative column reconciliation (parity with SessionSchemaMixin)
# ---------------------------------------------------------------------------
#
# WHY THIS EXISTS
# ---------------
# Before this, the two backends managed schema by *different mechanisms* and
# only one was self-healing:
#
#   SQLite   — SessionSchemaMixin._reconcile_columns() diffs live columns against
#              SCHEMA_SQL on every startup and ALTER TABLE ADD COLUMNs whatever
#              is missing. Declaring a column is sufficient.
#   Postgres — a hand-maintained list of ALTER TABLE ... ADD COLUMN statements
#              in _PG_ONLY_MIGRATIONS. Declaring a column did nothing until a
#              human also wrote the matching ALTER.
#
# So the standing invariant was: *any column added to SCHEMA_SQL is automatically
# live on SQLite and silently absent on Postgres.* It failed at WARNING with a
# normal-looking turn, so it cost the deployment its entire session history before
# anyone noticed. Fixing the drifted columns alone fixes the instance; this
# function fixes the generator.
#
# SQLITE-DECLARED TYPES ON POSTGRES
# ---------------------------------
# The declared type comes from SCHEMA_SQL, i.e. SQLite's dialect, so it is
# mapped to the Postgres equivalent (_PG_TYPE_MAP) before use. Only the small
# closed set of types SCHEMA_SQL actually uses is mapped; an unrecognized type
# fails initialization rather than being guessed at: an unusable store must not
# be handed to the transcript writer.
#
# ADD COLUMN ONLY — NEVER CREATE TABLE
# ------------------------------------
# This mirrors the SQLite reconciler's contract exactly: it reconciles columns
# on tables that already exist and skips tables that do not. That is not an
# omission, it is the Chesterton's-fence boundary. A reconciler that created
# every declared table would still invent tables without an explicit ownership
# decision. Tables that genuinely belong on both backends, including the PG3
# extra-ledger inventory, are declared in SCHEMA_SQL_POSTGRES and created there.

# SQLite declared type -> Postgres equivalent. Closed set: exactly the types
# SCHEMA_SQL uses today. Anything else fails reconciliation (see above).
_PG_TYPE_MAP = {
    "TEXT": "TEXT",
    "INTEGER": "INTEGER",
    "REAL": "DOUBLE PRECISION",
    "BLOB": "BYTEA",
    "": "TEXT",  # SQLite allows a typeless column; TEXT is the safe analogue
}


def _pg_column_type(declared: str) -> Optional[str]:
    """Map a SQLite column declaration to its Postgres equivalent.

    *declared* is what ``_parse_schema_columns`` reconstructs — a base type
    optionally followed by ``NOT NULL`` and/or ``DEFAULT <expr>``. The base type
    is translated via ``_PG_TYPE_MAP``; the constraint tail is passed through
    unchanged (``NOT NULL DEFAULT 0`` is valid in both dialects).

    Returns ``None`` for an unmapped base type so the caller can refuse the
    upgrade rather than emit a guessed ADD COLUMN.
    """
    parts = declared.split()
    base = parts[0].upper() if parts else ""
    # A bare constraint keyword means the column was declared with no type.
    if base in ("NOT", "DEFAULT"):
        base, tail = "", parts
    else:
        tail = parts[1:]
    mapped = _PG_TYPE_MAP.get(base)
    if mapped is None:
        return None
    return " ".join([mapped, *tail]) if tail else mapped


def reconcile_postgres_columns(conn: Any, schema_sql: str) -> List[str]:
    """ADD any column declared in *schema_sql* that is absent from Postgres.

    The PostgreSQL analogue of ``SessionSchemaMixin._reconcile_columns``.
    Runs on every connect; idempotent. Returns the ``table.column`` names it
    added, for logging and for tests to assert on.

    Live columns are read from ``information_schema.columns`` in ONE query
    (not per-table) so the cost is a single round trip regardless of table
    count. Only tables that already exist are touched — see the module note
    above on why this never CREATEs a table.

    A missing required column that cannot be added aborts startup. Reporting
    success here would defer the error to the next transcript write.
    """
    declared = SessionSchemaMixin._parse_schema_columns(schema_sql)

    raw = conn.raw if hasattr(conn, "raw") else conn
    live: Dict[str, set] = {}
    for table_name, column_name in raw.execute(
        "SELECT table_name, column_name FROM information_schema.columns"
        " WHERE table_schema = current_schema()"
    ).fetchall():
        live.setdefault(table_name, set()).add(column_name)

    added: List[str] = []
    for table_name, columns in declared.items():
        live_cols = live.get(table_name)
        if live_cols is None:
            # Table absent on Postgres. Creating it here is not this function's
            # job; cross-backend tables belong in SCHEMA_SQL_POSTGRES. DEBUG,
            # not WARNING, because optional SQLite feature tables can still be
            # absent in a valid steady state.
            logger.debug(
                "pg reconcile: table %s not present on Postgres, skipping",
                table_name,
            )
            continue
        for column_name, declared_type in columns.items():
            if column_name in live_cols:
                continue
            pg_type = _pg_column_type(declared_type)
            if pg_type is None:
                raise RuntimeError(
                    f"PostgreSQL schema cannot represent {table_name}.{column_name} "
                    f"with declared type {declared_type!r}"
                )
            try:
                raw.execute(
                    f'ALTER TABLE "{table_name}"'
                    f' ADD COLUMN IF NOT EXISTS "{column_name}" {pg_type}'
                )
            except Exception as exc:
                raise RuntimeError(
                    f"PostgreSQL schema could not add required column {table_name}.{column_name}"
                ) from exc
            added.append(f"{table_name}.{column_name}")

    if added:
        # INFO, not DEBUG: a column appearing here means the declarative
        # schema moved and Postgres caught up on its own. That is exactly the
        # event that was invisible before, so it gets a visible line.
        logger.info("pg reconcile: added missing columns: %s", ", ".join(added))
    return added


def init_postgres_topic_schema(conn: Any) -> None:
    """Provision topic tables only on explicit /topic opt-in or source migration."""
    from hermes_state_telegram import _TOPIC_TABLES

    raw = conn.raw if hasattr(conn, "raw") else conn
    for table, _columns, ddl in _TOPIC_TABLES:
        # SQLite REAL is a double. PostgreSQL REAL is single precision and
        # cannot preserve epoch timestamps, so spell the type explicitly.
        ddl = re.sub(r"\bREAL\b", "DOUBLE PRECISION", ddl)
        raw.execute(f"CREATE TABLE IF NOT EXISTS {table} ({ddl})")
    raw.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_telegram_dm_topic_bindings_session "
        "ON telegram_dm_topic_bindings(session_id)"
    )
    raw.execute(
        "CREATE INDEX IF NOT EXISTS idx_telegram_dm_topic_bindings_user "
        "ON telegram_dm_topic_bindings(profile_name, user_id, chat_id)"
    )
