"""Schema contracts and upgrade orchestration without a running PostgreSQL.

SQLite executes the shared schema as the column/index oracle. The upgrade
harness also executes real DDL and preserves rows, adapting only PostgreSQL's
identity/conditional-ALTER syntax and catalog lookup. PostgreSQL engine/dialect
behavior is covered separately by the live parity tests.
"""

import re
import sqlite3

import pytest

from hermes_state_common import DEFERRED_INDEX_SQL, SCHEMA_SQL, SCHEMA_VERSION
from hermes_state_dual import MIGRATED_TABLES
from hermes_state_pg_schema import (
    SCHEMA_SQL_POSTGRES, PostgresMigration, _PG_ONLY_MIGRATIONS, _apply_single_migration,
    _pg_column_type, _schema_statements, apply_postgres_migrations, init_postgres_schema,
    init_postgres_topic_schema, plan_postgres_migrations, postgres_applied_migrations,
    postgres_migration_version, postgres_schema_version, reconcile_postgres_columns,
)
from hermes_state_schema import SessionSchemaMixin
from tests.pg_trigger_harness import TriggerDDL

# ---------------------------------------------------------------------------
# Tables in SCHEMA_SQL that intentionally do NOT exist on PostgreSQL. This is
# an allowlist, not a blanket exemption — a NEW table added to
# SCHEMA_SQL and not to SCHEMA_SQL_POSTGRES fails the table-parity test until
# someone either adds it to Postgres or justifies it here. That is the point:
# the exemption has to be argued, not inherited.
# ---------------------------------------------------------------------------
SQLITE_LOCAL_TABLES = set()


def _columns(db):
    return {
        row[0]: {column[1]: column for column in db.execute(f'PRAGMA table_info("{row[0]}")')}
        for row in db.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")
    }


@pytest.fixture
def sqlite_schema():
    db = sqlite3.connect(":memory:")
    try:
        db.executescript(SCHEMA_SQL + DEFERRED_INDEX_SQL)
        yield db
    finally:
        db.close()


class _Rows:
    def __init__(self, rows):
        self.rows = rows

    def fetchall(self):
        return self.rows

    def fetchone(self):
        return self.rows[0] if self.rows else None


class _SchemaHarness:
    """Use SQLite's real DDL enforcement to exercise upgrade ordering and data retention."""
    def __init__(self):
        self.db = sqlite3.connect(":memory:", isolation_level=None)
        self.db.row_factory = sqlite3.Row
        self.raw = self
        self.executed = []
        self.fail_on = None
        self.trigger_ddl = TriggerDDL(self.db)

    def execute(self, sql, params=()):
        self.executed.append(sql)
        if self.fail_on and self.fail_on in sql:
            raise PermissionError("injected schema permission failure")
        trigger_result = self.trigger_ddl.execute(sql)
        if trigger_result is not None:
            return trigger_result
        if "information_schema.columns" in sql:
            return _Rows([(table, column) for table, cols in _columns(self.db).items() for column in cols])
        if "CREATE EXTENSION" in sql or "USING GIN" in sql:
            raise PermissionError("extension/index optimization unavailable in this harness")
        sql = re.sub(r"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY", sql)
        sql = sql.replace("CREATE INDEX CONCURRENTLY", "CREATE INDEX")
        alter = re.match(r'ALTER\s+TABLE\s+"?(\w+)"?\s+ADD\s+COLUMN\s+IF\s+NOT\s+EXISTS\s+"?(\w+)"?', sql, re.I)
        if alter:
            if alter.group(2) in _columns(self.db).get(alter.group(1), {}):
                return _Rows([])
            sql = re.sub(r"ADD\s+COLUMN\s+IF\s+NOT\s+EXISTS", "ADD COLUMN", sql, flags=re.I)
        return self.db.execute(sql.replace("%s", "?"), params)

    def commit(self):
        self.db.commit()


@pytest.fixture
def pg_schema():
    conn = _SchemaHarness()
    try:
        yield conn
    finally:
        conn.db.close()


def _seed_old_store(conn):
    conn.execute("CREATE TABLE schema_version(version INTEGER NOT NULL UNIQUE)")
    conn.execute("INSERT INTO schema_version VALUES (?)", (SCHEMA_VERSION - 1,))
    conn.execute("CREATE TABLE sessions(id TEXT PRIMARY KEY, source TEXT NOT NULL, started_at REAL NOT NULL)")
    conn.execute("CREATE TABLE messages(id INTEGER PRIMARY KEY, session_id TEXT NOT NULL, role TEXT NOT NULL, "
                 "content TEXT, timestamp REAL NOT NULL)")
    conn.execute("INSERT INTO sessions VALUES ('history', 'cli', 1.0)")
    conn.execute("INSERT INTO messages VALUES (1, 'history', 'user', 'original history', 2.0)")


def _shared_indexes(db):
    return {
        row[0] for row in db.execute(
            "SELECT name, tbl_name FROM sqlite_master WHERE type='index' AND sql IS NOT NULL"
        ) if row[1] not in SQLITE_LOCAL_TABLES
    }


def test_fresh_postgres_declaration_covers_shared_columns(sqlite_schema, pg_schema):
    # Execute the actual PostgreSQL declaration through the DDL harness, rather
    # than inferring column names from Python source or freezing a column list.
    for statement in _schema_statements(SCHEMA_SQL_POSTGRES):
        pg_schema.execute(statement)
    pg_tables = _columns(pg_schema.db)
    for table, columns in _columns(sqlite_schema).items():
        if table not in SQLITE_LOCAL_TABLES:
            assert table in pg_tables
            assert set(columns) <= set(pg_tables[table])
    assert SQLITE_LOCAL_TABLES.isdisjoint(pg_tables)
    assert _shared_indexes(sqlite_schema) <= _shared_indexes(pg_schema.db)


def test_upgrade_reconciles_indexed_columns_before_building_indexes(sqlite_schema, pg_schema):
    _seed_old_store(pg_schema)
    init_postgres_schema(pg_schema, SCHEMA_VERSION)
    # A premature CREATE INDEX on active/display_order/session_key would have
    # raised against the real old tables in this harness.
    assert tuple(pg_schema.execute("SELECT id, content, _compressed_summary FROM messages").fetchone()) == (
        1, "original history", 0,
    )
    assert postgres_schema_version(pg_schema) == SCHEMA_VERSION
    assert _shared_indexes(sqlite_schema) <= _shared_indexes(pg_schema.db)
    for table, columns in _columns(sqlite_schema).items():
        if table not in SQLITE_LOCAL_TABLES:
            assert set(columns) <= set(_columns(pg_schema.db)[table])
    init_postgres_schema(pg_schema, SCHEMA_VERSION)
    assert pg_schema.execute("SELECT COUNT(*) FROM messages").fetchone()[0] == 1
    assert pg_schema.execute("SELECT COUNT(*) FROM sessions").fetchone()[0] == 1


@pytest.mark.parametrize("legacy", [False, True])
def test_pending_fts_probe_uses_an_index_after_initialization(pg_schema, legacy):
    if legacy:
        _seed_old_store(pg_schema)
        # An old ledger may say the optional FTS migration ran while its
        # column is absent. Required initialization must still converge.
        pg_schema.execute("CREATE TABLE pg_migration_version(version INTEGER NOT NULL UNIQUE)")
        for migration in _PG_ONLY_MIGRATIONS:
            if migration.optional:
                pg_schema.execute("INSERT INTO pg_migration_version VALUES (?)", (migration.version,))
    init_postgres_schema(pg_schema, SCHEMA_VERSION)
    if not legacy:
        pg_schema.execute("INSERT INTO sessions(id, source, started_at) VALUES ('history', 'cli', 1.0)")
        pg_schema.execute("INSERT INTO messages(id, session_id, role, content, timestamp) "
                          "VALUES (1, 'history', 'user', 'original history', 2.0)")

    probe = "SELECT 1 FROM messages WHERE fts_content IS NULL LIMIT 1"
    # Exercise the real predicate/index relationship without freezing the
    # index name or reading Python source. SQLite's planner also understands
    # the partial-index declaration executed by this harness.
    assert any("INDEX" in row[3] for row in pg_schema.execute("EXPLAIN QUERY PLAN " + probe))
    assert pg_schema.execute(probe).fetchone() is not None
    pg_schema.execute("UPDATE messages SET fts_content = 'indexed' WHERE id = 1")
    assert pg_schema.execute(probe).fetchone() is None
    pg_schema.execute("INSERT INTO messages(id, session_id, role, content, timestamp) "
                      "VALUES (2, 'history', 'user', 'new unindexed history', 3.0)")
    assert pg_schema.execute(probe).fetchone() is not None


@pytest.mark.parametrize("statement, error, message", [
    ('ADD COLUMN IF NOT EXISTS "_compressed_summary"', RuntimeError, "required column messages._compressed_summary"),
    ("CREATE INDEX IF NOT EXISTS idx_messages_display_page", PermissionError, "injected"),
    ("CREATE OR REPLACE TRIGGER messages_projection_update", PermissionError, "injected"),
])
def test_failed_required_schema_cannot_report_a_successful_upgrade(pg_schema, statement, error, message):
    _seed_old_store(pg_schema)
    pg_schema.fail_on = statement
    with pytest.raises(error, match=message):
        init_postgres_schema(pg_schema, SCHEMA_VERSION)
    assert postgres_schema_version(pg_schema) == SCHEMA_VERSION - 1
    last_required = max(m.version for m in _PG_ONLY_MIGRATIONS if not m.optional)
    assert last_required not in postgres_applied_migrations(pg_schema)
    assert pg_schema.execute("SELECT content FROM messages").fetchone()[0] == "original history"
    pg_schema.fail_on = None
    init_postgres_schema(pg_schema, SCHEMA_VERSION)
    assert postgres_schema_version(pg_schema) == SCHEMA_VERSION


def test_reconciler_only_adds_missing_columns_and_preserves_defaults(pg_schema):
    pg_schema.execute("CREATE TABLE sessions(id TEXT PRIMARY KEY)")
    pg_schema.execute("INSERT INTO sessions VALUES ('existing')")
    schema = "CREATE TABLE sessions(id TEXT PRIMARY KEY, retries INTEGER NOT NULL DEFAULT 0, last_seen REAL);"
    assert set(reconcile_postgres_columns(pg_schema, schema)) == {"sessions.retries", "sessions.last_seen"}
    assert tuple(pg_schema.execute("SELECT retries, last_seen FROM sessions").fetchone()) == (0, None)
    assert reconcile_postgres_columns(pg_schema, schema) == []


def test_reconciler_does_not_provision_tables(pg_schema):
    assert reconcile_postgres_columns(pg_schema, SCHEMA_SQL) == []
    assert _columns(pg_schema.db) == {}


def test_unrepresentable_required_column_fails_closed(pg_schema):
    pg_schema.execute("CREATE TABLE sessions(id TEXT PRIMARY KEY)")
    with pytest.raises(RuntimeError, match="cannot represent sessions.exotic"):
        reconcile_postgres_columns(pg_schema, "CREATE TABLE sessions(id TEXT PRIMARY KEY, exotic GEOMETRY)")
    assert set(_columns(pg_schema.db)["sessions"]) == {"id"}


@pytest.mark.parametrize("declared, expected", [
    ("INTEGER NOT NULL DEFAULT 0", "INTEGER NOT NULL DEFAULT 0"),
    ("REAL", "DOUBLE PRECISION"),
    ("BLOB", "BYTEA"),
    ("TEXT NOT NULL DEFAULT ''", "TEXT NOT NULL DEFAULT ''"),
])
def test_type_mapping_preserves_value_capacity_and_constraints(declared, expected):
    assert _pg_column_type(declared) == expected


def test_every_shared_column_type_can_be_reconciled():
    for table, columns in SessionSchemaMixin._parse_schema_columns(SCHEMA_SQL).items():
        if table not in SQLITE_LOCAL_TABLES:
            for name, declared in columns.items():
                assert _pg_column_type(declared) is not None, f"{table}.{name}: {declared}"


def test_postgres_migrations_record_to_their_own_ledger(pg_schema):
    init_postgres_schema(pg_schema, SCHEMA_VERSION)
    shared_before = postgres_schema_version(pg_schema)
    version = postgres_migration_version(pg_schema) + 1
    migration = PostgresMigration(version, "CREATE TABLE IF NOT EXISTS migration_probe(id INTEGER)")
    _apply_single_migration(pg_schema, migration)
    _apply_single_migration(pg_schema, migration)
    assert postgres_migration_version(pg_schema) == version
    assert postgres_schema_version(pg_schema) == shared_before
    assert pg_schema.execute("SELECT COUNT(*) FROM pg_migration_version WHERE version = ?", (version,)).fetchone()[0] == 1


def test_migration_planning_ignores_a_newer_shared_schema_version(pg_schema):
    init_postgres_schema(pg_schema, SCHEMA_VERSION)
    pg_schema.execute("DELETE FROM pg_migration_version")
    future_shared = SCHEMA_VERSION + max(m.version for m in _PG_ONLY_MIGRATIONS) + 1
    pg_schema.execute("INSERT INTO schema_version VALUES (?)", (future_shared,))
    apply_postgres_migrations(pg_schema)
    assert {m.version for m in _PG_ONLY_MIGRATIONS if not m.optional} <= postgres_applied_migrations(pg_schema)
    assert postgres_schema_version(pg_schema) == future_shared
    init_postgres_schema(pg_schema, SCHEMA_VERSION)
    assert postgres_schema_version(pg_schema) == future_shared


def test_failed_optional_migration_is_retried_below_high_water_mark(pg_schema, monkeypatch):
    import hermes_state_pg_schema as schema

    pg_schema.execute("CREATE TABLE pg_migration_version(version INTEGER NOT NULL UNIQUE)")
    migrations = [
        PostgresMigration(1, "CREATE TABLE IF NOT EXISTS optional_probe(id INTEGER)", optional=True),
        PostgresMigration(2, "CREATE TABLE IF NOT EXISTS required_probe(id INTEGER)"),
    ]
    monkeypatch.setattr(schema, "_PG_ONLY_MIGRATIONS", migrations)
    pg_schema.fail_on = "CREATE TABLE IF NOT EXISTS optional_probe"
    apply_postgres_migrations(pg_schema)
    assert postgres_applied_migrations(pg_schema) == {2}
    pg_schema.fail_on = None
    apply_postgres_migrations(pg_schema)
    assert postgres_applied_migrations(pg_schema) == {1, 2}
    assert {"optional_probe", "required_probe"} <= set(_columns(pg_schema.db))


def test_required_migration_failure_is_not_recorded(pg_schema, monkeypatch):
    import hermes_state_pg_schema as schema

    pg_schema.execute("CREATE TABLE pg_migration_version(version INTEGER NOT NULL UNIQUE)")
    migration = PostgresMigration(1, "CREATE TABLE IF NOT EXISTS required_probe(id INTEGER)")
    monkeypatch.setattr(schema, "_PG_ONLY_MIGRATIONS", [migration])
    pg_schema.fail_on = "CREATE TABLE IF NOT EXISTS required_probe"
    with pytest.raises(PermissionError, match="injected"):
        apply_postgres_migrations(pg_schema)
    assert postgres_applied_migrations(pg_schema) == set()


def test_extension_optimizations_are_optional():
    for migration in _PG_ONLY_MIGRATIONS:
        if "CREATE EXTENSION" in migration.sql.upper() or "GIN_TRGM_OPS" in migration.sql.upper():
            assert migration.optional


def test_every_migrated_table_is_declared_in_postgres_schema():
    """COPY/diff targets must have a destination table on PostgreSQL."""
    declared = {
        m.group(1).strip('"')
        for m in re.finditer(r"CREATE TABLE IF NOT EXISTS\s+([\w\"]+)", SCHEMA_SQL_POSTGRES)
    }
    missing = sorted(set(MIGRATED_TABLES) - declared)
    assert not missing, (
        "tables selected for COPY/hash diff but absent from "
        f"SCHEMA_SQL_POSTGRES: {missing}"
    )


def test_planner_is_empty_when_all_versions_are_recorded():
    versions = {m.version for m in _PG_ONLY_MIGRATIONS}
    assert plan_postgres_migrations(max(versions), versions) == []
    first = min(versions)
    assert {m.version for m in plan_postgres_migrations(first)} == versions - {first}


def test_migration_versions_are_unique_and_ordered():
    versions = [m.version for m in _PG_ONLY_MIGRATIONS]
    assert versions == sorted(set(versions))


def test_topic_schema_remains_opt_in_and_preserves_timestamp_types(pg_schema):
    from hermes_state_telegram import _TOPIC_TABLES

    init_postgres_schema(pg_schema, SCHEMA_VERSION)
    topic_tables = {table for table, _columns_sql, _ddl in _TOPIC_TABLES}
    assert topic_tables.isdisjoint(_columns(pg_schema.db))
    init_postgres_topic_schema(pg_schema)
    init_postgres_topic_schema(pg_schema)
    columns = _columns(pg_schema.db)
    assert topic_tables <= set(columns)
    for table, _column_sql, ddl in _TOPIC_TABLES:
        declared = SessionSchemaMixin._parse_schema_columns(f"CREATE TABLE {table} ({ddl})")[table]
        for name, declaration in declared.items():
            if declaration.startswith("REAL"):
                assert columns[table][name][2] == "DOUBLE PRECISION"


def test_migration_column_and_default_coverage(sqlite_schema):
    from hermes_state_pg_import import _NOT_NULL_DEFAULTS, _derive_migration_columns

    for table in ("sessions", "messages"):
        cols = _columns(sqlite_schema)[table]
        assert _derive_migration_columns(table) == list(cols)
        for name, info in cols.items():
            if info[3] and info[4] is not None:
                assert (table, name) in _NOT_NULL_DEFAULTS


def test_projection_upgrade_invalidates_existing_cached_fields_only_once(pg_schema):
    init_postgres_schema(pg_schema, SCHEMA_VERSION)
    pg_schema.execute("INSERT INTO sessions(id, source, started_at) VALUES ('history', 'cli', 1.0)")
    pg_schema.execute("INSERT INTO messages(id, session_id, role, content, timestamp) "
                      "VALUES (1, 'history', 'user', 'canonical history', 2.0)")
    projection_version = next(m.version for m in _PG_ONLY_MIGRATIONS if m.raw_statements)
    pg_schema.execute("DELETE FROM pg_migration_version WHERE version = ?", (projection_version,))
    pg_schema.execute(
        "UPDATE messages SET display_identity = ?, display_order = ?, fts_content = ?", (b"stale", 99, "stale text"),
    )
    init_postgres_schema(pg_schema, SCHEMA_VERSION)
    assert tuple(pg_schema.execute(
        "SELECT content, display_identity, display_order, fts_content FROM messages"
    ).fetchone()) == ("canonical history", None, None, None)
    assert projection_version in postgres_applied_migrations(pg_schema)

    # Reopening needs neither trigger-owner permissions nor another archive-wide
    # backfill after the projection migration succeeded.
    rebuilt = (b"rebuilt", 1, "rebuilt vector")
    pg_schema.execute("UPDATE messages SET display_identity = ?, display_order = ?, fts_content = ?", rebuilt)
    pg_schema.fail_on = "CREATE OR REPLACE"
    init_postgres_schema(pg_schema, SCHEMA_VERSION)
    assert tuple(pg_schema.execute(
        "SELECT display_identity, display_order, fts_content FROM messages"
    ).fetchone()) == rebuilt
