"""Real PostgreSQL contract tests for host-registered kanban service tables.

The shape follows ``test_kanban_persistence.py``: a real py-pglite server, the
real adapter, no stubbed cursor. What is measured here is the boundary between
the core's seven tables and the tables a host application owns in the same
schema -- that an unregistered one is still refused, that a registered one
resolves conflicts and identity from its own declaration, and that a projects
dialect reusing the adapter does not inherit the kanban registration.
"""

from __future__ import annotations

import json
import sqlite3

import psycopg
import pytest
from py_pglite import PGliteConfig, PGliteManager

from hermes_cli import kanban_db as kb
from hermes_cli import kanban_persistence
from hermes_cli.kanban_persistence import set_service_tables
from hermes_cli.kanban_postgres import PostgresDialect

SERVICE_TABLES = {
    "claim_attempts": {
        "key": ("attempt_id",),
        "identity": False,
        "tenant_scope": "task",
        "tenant_key": "card_id",
    },
    "service_notes": {
        "key": ("id",),
        "identity": True,
        "tenant_scope": "column",
        "tenant_key": "board",
    },
}

SERVICE_DDL = (
    """
    CREATE TABLE claim_attempts (
        card_id TEXT NOT NULL,
        generation BIGINT NOT NULL CHECK (generation > 0),
        attempt_id TEXT PRIMARY KEY,
        claim_request_id TEXT,
        worker_id TEXT NOT NULL,
        claimed_at BIGINT NOT NULL,
        revoked_at BIGINT,
        UNIQUE (card_id, generation)
    )
    """,
    """
    CREATE TABLE service_notes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        board TEXT NOT NULL,
        note TEXT NOT NULL
    )
    """,
    "CREATE TABLE unregistered_side_table (id TEXT PRIMARY KEY, payload TEXT)",
)


class KanbanPGliteManager(PGliteManager):
    """Adapt py-pglite 0.5.3 startup to the pinned socket server API."""

    def _generate_unix_js_content(self, ext_requires_str, extensions_obj_str):
        source = super()._generate_unix_js_content(ext_requires_str, extensions_obj_str)
        for old, new in (
            ("const db = new PGlite({", "const db = await PGlite.create({"),
            ("path: SOCKET_PATH,", "path: SOCKET_PATH, maxConnections: 16,"),
        ):
            assert source.count(old) == 1
            source = source.replace(old, new)
        return source


@pytest.fixture(scope="module")
def pg_server(tmp_path_factory):
    work_dir = tmp_path_factory.mktemp("kanban-service-pg")
    (work_dir / "package.json").write_text(
        json.dumps({
            "private": True,
            "dependencies": {
                "@electric-sql/pglite": "0.3.16",
                "@electric-sql/pglite-socket": "0.0.22",
            },
        }),
        encoding="utf-8",
    )
    manager = KanbanPGliteManager(PGliteConfig(work_dir=work_dir))
    try:
        manager.start()
        yield manager.get_connection_string().replace(
            "postgresql+psycopg://", "postgresql://"
        )
    finally:
        manager.stop()


@pytest.fixture
def registered(pg_server, monkeypatch):
    """A live PostgreSQL kanban connection whose service tables are registered."""
    monkeypatch.delenv("HERMES_KANBAN_BACKEND", raising=False)
    monkeypatch.delenv("HERMES_KANBAN_POSTGRES_DSN", raising=False)
    with psycopg.connect(pg_server, autocommit=True) as raw:
        raw.execute("DROP SCHEMA public CASCADE")
        raw.execute("CREATE SCHEMA public")
    conn = kb.connect(backend="postgres", postgres_dsn=pg_server)
    with kb.write_txn(conn):
        for statement in SERVICE_DDL:
            conn.execute(statement)
    set_service_tables(SERVICE_TABLES)
    try:
        yield conn
    finally:
        set_service_tables(None)
        conn.close()


def _claim_row(conn, attempt_id):
    return conn.execute(
        "SELECT * FROM claim_attempts WHERE attempt_id = ?", (attempt_id,)
    ).fetchone()


def test_an_unregistered_table_is_still_refused(registered):
    """Registration widens the contract by name; it does not open it."""
    with pytest.raises(ValueError, match="outside the kanban persistence contract"):
        with kb.write_txn(registered):
            registered.execute(
                "INSERT INTO unregistered_side_table (id, payload) VALUES (?, ?)",
                ("a", "b"),
            )
    assert not registered.in_transaction


def test_a_registered_table_accepts_the_write_that_the_contract_refused(registered):
    task_id = kb.create_task(registered, title="claimable")
    with kb.write_txn(registered):
        registered.execute(
            "INSERT INTO claim_attempts"
            " (card_id, generation, attempt_id, claim_request_id, worker_id, claimed_at)"
            " VALUES (?, ?, ?, ?, ?, ?)",
            (task_id, 1, "attempt-1", "req-1", "worker-1", 100),
        )
    assert _claim_row(registered, "attempt-1")["worker_id"] == "worker-1"


def test_the_conflict_key_comes_from_the_declaration(registered):
    """``INSERT OR IGNORE`` resolves against the declared key, not a guess."""
    task_id = kb.create_task(registered, title="racing claims")
    with kb.write_txn(registered):
        for worker in ("worker-1", "worker-2"):
            registered.execute(
                "INSERT OR IGNORE INTO claim_attempts"
                " (card_id, generation, attempt_id, worker_id, claimed_at)"
                " VALUES (?, ?, ?, ?, ?)",
                (task_id, 1, "attempt-2", worker, 100),
            )
    assert _claim_row(registered, "attempt-2")["worker_id"] == "worker-1"

    with kb.write_txn(registered):
        registered.execute(
            "INSERT OR REPLACE INTO claim_attempts"
            " (card_id, generation, attempt_id, worker_id, claimed_at)"
            " VALUES (?, ?, ?, ?, ?)",
            (task_id, 1, "attempt-2", "worker-3", 200),
        )
    replaced = _claim_row(registered, "attempt-2")
    assert replaced["worker_id"] == "worker-3"
    assert replaced["claim_request_id"] is None


def test_a_constraint_the_key_does_not_cover_still_raises(registered):
    """The declared key is the conflict target, not a blanket ``DO NOTHING``."""
    task_id = kb.create_task(registered, title="unique generation")
    with kb.write_txn(registered):
        registered.execute(
            "INSERT INTO claim_attempts"
            " (card_id, generation, attempt_id, worker_id, claimed_at)"
            " VALUES (?, ?, ?, ?, ?)",
            (task_id, 7, "attempt-3", "worker-1", 100),
        )
    with pytest.raises(sqlite3.IntegrityError):
        with kb.write_txn(registered):
            registered.execute(
                "INSERT OR IGNORE INTO claim_attempts"
                " (card_id, generation, attempt_id, worker_id, claimed_at)"
                " VALUES (?, ?, ?, ?, ?)",
                (task_id, 7, "attempt-4", "worker-2", 100),
            )
    assert _claim_row(registered, "attempt-4") is None
    assert not registered.in_transaction


def test_identity_is_answered_by_the_declaration(registered):
    """``lastrowid`` is filled for a declared identity and left alone otherwise."""
    with kb.write_txn(registered):
        note = registered.execute(
            "INSERT INTO service_notes (board, note) VALUES (?, ?)",
            ("dev-guild", "first"),
        )
        assert note.lastrowid > 0
        attempt = registered.execute(
            "INSERT INTO claim_attempts"
            " (card_id, generation, attempt_id, worker_id, claimed_at)"
            " VALUES (?, ?, ?, ?, ?)",
            ("t_none", 1, "attempt-5", "worker-1", 100),
        )
        assert attempt.lastrowid is None


def test_a_rolled_back_service_write_leaves_nothing_behind(registered):
    with pytest.raises(ValueError, match="abort"):
        with kb.write_txn(registered):
            registered.execute(
                "INSERT INTO claim_attempts"
                " (card_id, generation, attempt_id, worker_id, claimed_at)"
                " VALUES (?, ?, ?, ?, ?)",
                ("t_none", 1, "attempt-6", "worker-1", 100),
            )
            raise ValueError("abort")
    assert _claim_row(registered, "attempt-6") is None
    assert not registered.in_transaction


def test_clearing_the_registration_closes_the_contract_again(registered):
    set_service_tables(None)
    assert kanban_persistence.has_service_tables() is False
    with pytest.raises(ValueError, match="outside the kanban persistence contract"):
        with kb.write_txn(registered):
            registered.execute(
                "INSERT INTO claim_attempts"
                " (card_id, generation, attempt_id, worker_id, claimed_at)"
                " VALUES (?, ?, ?, ?, ?)",
                ("t_none", 1, "attempt-7", "worker-1", 100),
            )


def test_another_store_reusing_the_adapter_does_not_inherit_the_registration():
    """A projects-shaped dialect keeps the closed core list."""
    set_service_tables(SERVICE_TABLES)
    try:
        kanban = PostgresDialect()
        assert kanban.keys_for("claim_attempts") == ("attempt_id",)

        class _OtherStoreDialect(PostgresDialect):
            store_name = "projects"
            table_keys = {"projects": ("id",)}

        other = _OtherStoreDialect()
        assert other.keys_for("claim_attempts") is None
        assert other.has_identity("service_notes") is False
        with pytest.raises(ValueError, match="outside the projects"):
            other.check_table("claim_attempts")
    finally:
        set_service_tables(None)


@pytest.mark.parametrize(
    "declaration",
    [
        {"identity": False, "tenant_scope": "task", "tenant_key": "card_id"},
        {"key": (), "identity": False, "tenant_scope": "task", "tenant_key": "card_id"},
        {"key": "attempt_id", "identity": False, "tenant_scope": "task", "tenant_key": "card_id"},
        {"key": ("attempt id",), "identity": False, "tenant_scope": "task", "tenant_key": "card_id"},
        {"key": ("a", "a"), "identity": False, "tenant_scope": "task", "tenant_key": "card_id"},
        {"key": ("attempt_id",), "tenant_scope": "task", "tenant_key": "card_id"},
        {"key": ("attempt_id",), "identity": 1, "tenant_scope": "task", "tenant_key": "card_id"},
        {"key": ("attempt_id",), "identity": False, "tenant_key": "card_id"},
        {"key": ("attempt_id",), "identity": False, "tenant_scope": "unscoped", "tenant_key": "card_id"},
        {"key": ("attempt_id",), "identity": False, "tenant_scope": "task"},
        {"key": ("attempt_id",), "identity": False, "tenant_scope": "task", "tenant_key": "card_id", "extra": 1},
    ],
)
def test_an_incomplete_declaration_is_refused(declaration):
    with pytest.raises(ValueError):
        set_service_tables({"claim_attempts": declaration})
    assert kanban_persistence.has_service_tables() is False


def test_a_registration_cannot_shadow_a_core_table():
    with pytest.raises(ValueError, match="shadow a core kanban table"):
        set_service_tables({
            "tasks": {
                "key": ("id",),
                "identity": False,
                "tenant_scope": "column",
                "tenant_key": "board",
            }
        })
    assert kanban_persistence.TABLE_KEYS["tasks"] == ("id",)
    assert kanban_persistence.has_service_tables() is False


def test_an_empty_or_non_mapping_registration_is_refused():
    for value in ({}, (), "claim_attempts", 0):
        with pytest.raises(ValueError, match="non-empty mapping"):
            set_service_tables(value)
    assert kanban_persistence.has_service_tables() is False
